[build]
builder = "nixpacks"
buildCommand = "npm run build && npm run migrate:up"

[deploy]
startCommand = "node dist/app.js"
healthcheckPath = "/health"
healthcheckTimeout = 5
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
